**What is Data preprocessing?**




*  ** Data**:  text,image,video and audio



*  Data preprocessing is a process to convert raw data into meaningful data using different techniques.

Why DataProcessing is important?

Data in the real world is dirty


*   Incomplete
*   Noicy
*   Inconsistenrt
*   Duplicate




Data quality elemets:


*   Accuracy
*   Completeness
*   Consistency
*   Believablity
*   Interpretablility

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dict1 ={
    'Name': ['Priyang','Aadhya','Krisha','Vedant','Parshv',
            'Mittal','Archana'],
    'Marks':[98,89,99,87,90,83,99],
    'Gender':['Male','Female','Female','Male','Male',
              'Female','Female']
}
df1=pd.DataFrame(dict1)
dict2 = {
    'Name':['Siya','Riya','Jiya','Diya','Shreya',
            'Jaya','Aditiya'],
    'Marks':[98,89,99,87,90,83,99],
    'Gender':['Female','Female','Female','Female','Female',
              'Female','Female']
}
df2=pd.DataFrame(dict2)
combined_df = df1.combine_first(df2)
display(combined_df)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [ ]:
df = pd.read_csv('/content/DataAnalyst - DataAnalyst.csv', on_bad_lines='skip', engine='python')
df

FileNotFoundError: [Errno 2] No such file or directory: '/content/DataAnalyst - DataAnalyst.csv'

In [ ]:
df_1 = pd.DataFrame({'ID':[1,2,3,5],
                     'Class':[9,10,2,11]})
df_1

In [ ]:
df_2 = pd.DataFrame({'ID':[1,2,3,4],
                     'Name':['A','B','C','D']})
df_2

In [ ]:
merge_df = pd.merge(df_1,df_2,how='left',on='ID',indicator=True)
merge_df

In [ ]:
merge_df = pd.merge(df_1,df_2,how='inner',on='ID',indicator=True)
merge_df

In [ ]:
merge_df = pd.merge(df_1,df_2,how='right',on='ID',indicator=True)
merge_df

In [ ]:
merge_df = pd.merge(df_1,df_2,how='outer',on='ID',indicator=True)
merge_df

In [ ]:
pd.merge(df_1,df_2,left_index=True,right_index=True)

In [ ]:
df1 = pd.DataFrame({'user':[101,102,103],'name':['Alice','Bob','Charlie']},index =[11,12,13])
# df1

df2 = pd.DataFrame({'user':[101,102,104],'age':[25,30,2]},index =[100,200,300])
# df2

In [ ]:
index_access = pd.merge(df1,df2,left_index = True, right_index = True)
index_access

In [ ]:
df21 = pd.DataFrame({'user':[101,102,103],'name':['Alice','Bob','Charlie']},index =[11,12,13])
df21

df22 = pd.DataFrame({'user':[101,102,104],'age':[25,30,2]},index =[11,12,13])
df22

In [ ]:
index_access = pd.merge(df21,df22,left_index = True, right_index = True)
index_access

In [ ]:
data = {
    'Age':[25,np.nan,30,22,np.nan],
    'City':['New York','Pairs','London',np.nan,'Paris'],
    'Score':[85,90,np.nan,78,88]

}

dataf = pd.DataFrame(data)
print("Original data: \n",dataf)

Original data:
     Age      City  Score
0  25.0  New York   85.0
1   NaN     Pairs   90.0
2  30.0    London    NaN
3  22.0       NaN   78.0
4   NaN     Paris   88.0

In [ ]:
dataf.isnull()

     Age   City  Score
0  False  False  False
1   True  False  False
2  False  False   True
3  False   True  False
4   True  False  False

In [ ]:
print(dataf.isnull().sum())

Age      2
City     1
Score    1
dtype: int64

In [ ]:
dataf.notnull()

     Age   City  Score
0   True   True   True
1  False   True   True
2   True   True  False
3   True  False   True
4  False   True   True

In [ ]:
print(dataf.notnull().sum())

Age      3
City     4
Score    4
dtype: int64

**Fillna() function:**

The fillna() function in pandas is used to fill missing values (NaN) in a DataFrame or Series. You can fill missing values with a specific value, or with a calculated value like the mean, median, or mode of the column. This helps to clean up your data for further analysis.

For example, in the code you have:

df_zero = dataf.fillna(0): This fills all NaN values in the dataf DataFrame with 0.
dataf['Age']=dataf['Age'].fillna(dataf['Age'].mean()): This fills the missing NaN values in the 'Age' column with the mean (average) of the existing 'Age' values.
dataf['City']=dataf['City'].fillna(dataf['City'].mode()[0]): This fills the missing NaN values in the 'City' column with the mode (most frequent value) of the existing 'City' values.

In [ ]:
#Fillna

In [ ]:
df_zero = dataf.fillna(0)

In [ ]:
dataf['Age']=dataf['Age'].fillna(dataf['Age'].mean())
dataf['City']=dataf['City'].fillna(dataf['City'].mode()[0])

dataf

         Age      City  Score
0  25.000000  New York   85.0
1  25.666667     Pairs   90.0
2  30.000000    London    NaN
3  22.000000    London   78.0
4  25.666667     Paris   88.0